name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          npm install
          npm run build
          env|sort
      -
        name: Env
        shell: bash
        run: |
          env|sort
      -
        name: Import GPG key
        uses: ./
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY_TEST }}
          PASSPHRASE: ${{ secrets.PASSPHRASE_TEST }}
